apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: test-component
  description: Just Test
  tags:
    - test
  links:
    - url: https://example.com/user
      title: Examples Users
      icon: user
    - url: https://example.com/group
      title: Example Group
      icon: group
    - url: https://example.com/cloud
      title: Link with Cloud Icon
      icon: cloud
    - url: https://example.com/dashboard
      title: Dashboard
      icon: dashboard
spec:
  type: service
  lifecycle: experimental
  owner: spadeace
  system: artist-engagement-portal
  dependsOn: ['resource:artists-db']
